version: '3.8'

services:
  spark-master:
    image: t1p0k/water-analysis-system-spark-master:latest
    container_name: spark-master-gpu
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_MODE: master
    networks:
      - water-network

  spark-worker:
    image: t1p0k/water-analysis-system-spark-worker:latest
    container_name: spark-worker-gpu
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER: spark://spark-master:7077
    networks:
      - water-network

  spark-runner:
    image: t1p0k/water-analysis-system-spark-runner:latest
    container_name: spark-runner-gpu
    depends_on:
      - spark-master
    networks:
      - water-network

  api:
    image: t1p0k/water-analysis-system-api:latest
    container_name: water-api
    ports:
      - "8000:8000"
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - water-network

  streamlit:
    image: t1p0k/water-analysis-system-streamlit:latest
    container_name: water-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000
    networks:
      - water-network

  redis:
    image: redis:7-alpine
    container_name: water-redis
    ports:
      - "6379:6379"
    networks:
      - water-network

  grafana:
    image: grafana/grafana:latest
    container_name: water-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - water-network

  prometheus:
    image: prom/prometheus:latest
    container_name: water-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - water-network

networks:
  water-network:
    driver: bridge
